#!/bin/sh
set -e

case "$1" in
    remove|upgrade|deconfigure)
        rm -rf /usr/share/abraflexi-order-status-changer/composer.lock /var/lib/composer/abraflexi-order-status-changer
    ;;

    failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac


#DEBHELPER#

exit 0
